/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import lapr.project.model.exhibitions.CentroExposicoes;
import lapr.project.model.submissions.Candidatura;
import lapr.project.ui.organizador.DefinirFAEUI;
/**
 *
 * @author TiagoSilvestre
 */
public class ConsultarCandidaturasRetiradasUI extends javax.swing.JFrame {

    private CentroExposicoes centroExpo;

    /**
     * Creates new form ConsultarCandidaturasRetiradasUI
     *
     * @param cExpo
     */
    public ConsultarCandidaturasRetiradasUI(CentroExposicoes cExpo) {
        this.centroExpo = cExpo;
        
        super.setTitle("Candidaturas retiradas");
        initComponents();
        inicializarLista();
        setLocationRelativeTo(null);
        super.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanelNorth = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLstCandidaturas = new javax.swing.JList<Candidatura>();
        jPanelSouth1 = new javax.swing.JPanel();
        btnInfo = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Candidaturas retiradas");

        jScrollPane1.setViewportView(jLstCandidaturas);

        javax.swing.GroupLayout jPanelNorthLayout = new javax.swing.GroupLayout(jPanelNorth);
        jPanelNorth.setLayout(jPanelNorthLayout);
        jPanelNorthLayout.setHorizontalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNorthLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelNorthLayout.setVerticalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnInfo.setText("Ver informação");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSouth1Layout = new javax.swing.GroupLayout(jPanelSouth1);
        jPanelSouth1.setLayout(jPanelSouth1Layout);
        jPanelSouth1Layout.setHorizontalGroup(
            jPanelSouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSouth1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnInfo)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelSouth1Layout.setVerticalGroup(
            jPanelSouth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSouth1Layout.createSequentialGroup()
                .addComponent(btnInfo)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanelNorth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelSouth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanelNorth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSouth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
       Candidatura c = jLstCandidaturas.getSelectedValue();
       if(c == null){
           JOptionPane.showMessageDialog(ConsultarCandidaturasRetiradasUI.this,
                    "Seleccione uma candidatura", "Consultar candidaturas retiradas", JOptionPane.ERROR_MESSAGE);
       }else{
           new CandidaturaInfoUI(c);
       }
    }//GEN-LAST:event_btnInfoActionPerformed
   
    
    private void inicializarLista() {
        final List<Candidatura> list = getCandidaturasRetiradas();

        if (list.isEmpty()) {
            this.jLstCandidaturas.setModel(new DefaultListModel<>());
        }

        DefaultListModel listModel = new DefaultListModel() {
            @Override
            public int getSize() {
                return list.size();
            }

            @Override
            public Object getElementAt(int i) {
                return list.get(i);
            }
        };

        this.jLstCandidaturas.setModel(listModel);
        this.jLstCandidaturas.setCellRenderer(new CellRenderer());
    }

    private class CellRenderer extends JLabel implements ListCellRenderer<Candidatura> {

        public CellRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getListCellRendererComponent(JList<? extends Candidatura> list, Candidatura r, int index, boolean isSelected, boolean cellHasFocus) {
            setText(r.getNomeEmpresa());

            if (isSelected) {
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            } else {
                setBackground(list.getBackground());
                setForeground(list.getForeground());
            }

            return this;
        }
    }
    
    private List<Candidatura> getCandidaturasRetiradas(){
        List<Candidatura> list = new ArrayList<>();
        
        for(Candidatura c : this.centroExpo.getListaCandidaturas().getListaCandidaturas()){
            if(c.isRetirada()){
                list.add(c);
            }
        }
        return list;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<Candidatura> jLstCandidaturas;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
