/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import java.awt.Component;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import lapr.project.controller.RetirarCandidaturaController;
import lapr.project.model.Retiravel;
import lapr.project.model.exhibitions.CentroExposicoes;

/**
 *
 * @author zero_
 */
public class RetirarCandidaturaUI extends javax.swing.JFrame {

    private RetirarCandidaturaController controller;

    /**
     * Creates new form RetirarCandidaturaUI
     */
    public RetirarCandidaturaUI(CentroExposicoes centroExposicoes) {
        this.controller = new RetirarCandidaturaController(centroExposicoes);

        super.setTitle("Remover Candidatura");

        initComponents();
        inicializarLista();

        setLocationRelativeTo(null);
        super.setVisible(true);
    }

    private void inicializarLista() {
        final List<Retiravel> listaRetiraveis = this.controller.getListaRetiraveis();

        if (listaRetiraveis.isEmpty()) {
            this.jListRetiraveis.setModel(new DefaultListModel<>());
            JOptionPane.showMessageDialog(this, "Não existem Retiraveis");
        }

        DefaultListModel listModel = new DefaultListModel() {
            @Override
            public int getSize() {
                return listaRetiraveis.size();
            }

            @Override
            public Object getElementAt(int i) {
                return listaRetiraveis.get(i);
            }
        };

        this.jListRetiraveis.setModel(listModel);
        this.jListRetiraveis.setCellRenderer(new CellRenderer());
    }

    private class CellRenderer extends JLabel implements ListCellRenderer<Retiravel> {

        public CellRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getListCellRendererComponent(JList<? extends Retiravel> list, Retiravel retiravel, int index, boolean isSelected, boolean cellHasFocus) {
            setText(retiravel.getNomeEmpresa());

            if (isSelected) {
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            } else {
                setBackground(list.getBackground());
                setForeground(list.getForeground());
            }

            return this;
        }

    }

    private void refreshJList() {
//        jListRetiraveis = new JList<>();
//        inicializarLista();
        jListRetiraveis.remove(jListRetiraveis.getSelectedIndex());
        jScrollPane1.validate();
        jScrollPane1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRetirar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListRetiraveis = new javax.swing.JList<>();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonRetirar.setText("Retirar Candidatura");
        jButtonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListRetiraveis);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRetirar)
                .addGap(18, 18, 18)
                .addComponent(jButtonOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarActionPerformed
        if (jListRetiraveis.getSelectedValue() != null) {
            if (this.controller.retirarCandidatura(jListRetiraveis.getSelectedValue())) {
                JOptionPane.showMessageDialog(RetirarCandidaturaUI.this,
                        "Candidatura retirada com sucesso", "Retirar Candidatura", JOptionPane.INFORMATION_MESSAGE);
                refreshJList();
            } else {
                JOptionPane.showMessageDialog(RetirarCandidaturaUI.this,
                        "Erro ao Retirar candidatura (Bad State?)", "Retirar Candidatura", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(RetirarCandidaturaUI.this,
                    "Selecione um retiravel", "Retirar Candidatura", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRetirarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonRetirar;
    private javax.swing.JList<Retiravel> jListRetiraveis;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
