/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import java.awt.Component;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import lapr.project.model.exhibitions.Exposicao;
import lapr.project.model.users.Organizador;
/**
 *
 * @author TiagoSilvestre
 */
public class ViewExpoUI extends javax.swing.JFrame {

    private Exposicao expo;

    /**
     * Creates new form CriarExposicaoUI
     *
     * @param e
     */
    public ViewExpoUI(Exposicao e) {
        this.expo = e;
        
        super.setTitle("View Exhibition");
        initComponents();
        inicializarLista();
        
        System.out.println(e);

        //TODO: Fix Gestor in expo issue
//        jTxtGestor.setText(this.expo.getGestor().getUtilizador().getUsername());
        txtTitulo.setText(this.expo.getTitle());
        txtDescricao.setText(this.expo.getDescription());
        txtLocal.setText(this.expo.getLocal());
        fTxtPeriodoRealizacaoInicio.setText(this.expo.getDataInicioRealizacao().toString());
        fTxtPeriodoRealizacaoFim.setText(this.expo.getDataFimRealizacao().toString());
        fTxtPeriodoSubmissaoInicio.setText(this.expo.getDataInicioSubmissao().toString());
        fTxtPeriodoSubmissaoFim.setText(this.expo.getDataFimSubmissao().toString());

        setLocationRelativeTo(null);
        super.setVisible(true);
    }

    private void inicializarLista() {
        final List<Organizador> lstOrg = this.expo.getListaOrganizadores().getLstOrganizadores();

        if (lstOrg.isEmpty()) {
            this.jLstOrganizadores.setModel(new DefaultListModel<>());
        }

        DefaultListModel listModel = new DefaultListModel() {
            @Override
            public int getSize() {
                return lstOrg.size();
            }

            @Override
            public Object getElementAt(int i) {
                return lstOrg.get(i);
            }
        };

        this.jLstOrganizadores.setModel(listModel);
        this.jLstOrganizadores.setCellRenderer(new CellRenderer());
    }

    private class CellRenderer extends JLabel implements ListCellRenderer<Organizador> {

        public CellRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getListCellRendererComponent(JList<? extends Organizador> list, Organizador user, int index, boolean isSelected, boolean cellHasFocus) {
            setText(user.getUtilizador().getUsername());

            if (isSelected) {
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            } else {
                setBackground(list.getBackground());
                setForeground(list.getForeground());
            }

            return this;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorth = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblLocal = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtLocal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtGestor = new javax.swing.JTextField();
        jPanelCenter = new javax.swing.JPanel();
        lblPeriodoRealizacao = new javax.swing.JLabel();
        lblPeriodoRealizacaoInicio = new javax.swing.JLabel();
        lblPeriodoRealizacaoFim = new javax.swing.JLabel();
        lblPeriodoSubmissao = new javax.swing.JLabel();
        lblPeriodoSubmissaoInicio = new javax.swing.JLabel();
        lblPeriodoSubmissaoFim = new javax.swing.JLabel();
        fTxtPeriodoRealizacaoInicio = new javax.swing.JFormattedTextField();
        fTxtPeriodoRealizacaoFim = new javax.swing.JFormattedTextField();
        fTxtPeriodoSubmissaoInicio = new javax.swing.JFormattedTextField();
        fTxtPeriodoSubmissaoFim = new javax.swing.JFormattedTextField();
        jPanelSouth = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLstOrganizadores = new javax.swing.JList<Organizador>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Expo info");

        lblTitulo.setText("Título:");

        lblDescricao.setText("Descrição:");

        lblLocal.setText("Local:");

        txtDescricao.setEditable(false);
        txtDescricao.setToolTipText("Descrição da Exposição");

        txtTitulo.setEditable(false);
        txtTitulo.setToolTipText("Título da Exposição");

        txtLocal.setEditable(false);
        txtLocal.setToolTipText("Local da Exposição");

        jLabel1.setText("Gestor:");

        jTxtGestor.setEditable(false);

        javax.swing.GroupLayout jPanelNorthLayout = new javax.swing.GroupLayout(jPanelNorth);
        jPanelNorth.setLayout(jPanelNorthLayout);
        jPanelNorthLayout.setHorizontalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNorthLayout.createSequentialGroup()
                        .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao)
                            .addComponent(lblTitulo)
                            .addComponent(lblLocal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(txtTitulo)
                            .addComponent(txtLocal)))
                    .addGroup(jPanelNorthLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtGestor)))
                .addContainerGap())
        );
        jPanelNorthLayout.setVerticalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNorthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtGestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocal)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblPeriodoRealizacao.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblPeriodoRealizacao.setText("Período de Realização");

        lblPeriodoRealizacaoInicio.setText("Início: ");

        lblPeriodoRealizacaoFim.setText("Fim:");

        lblPeriodoSubmissao.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblPeriodoSubmissao.setText("Período de Submissão");

        lblPeriodoSubmissaoInicio.setText("Início:");

        lblPeriodoSubmissaoFim.setText("Fim:");

        fTxtPeriodoRealizacaoInicio.setEditable(false);
        fTxtPeriodoRealizacaoInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        fTxtPeriodoRealizacaoInicio.setToolTipText("Data de início da realização da Exposição");

        fTxtPeriodoRealizacaoFim.setEditable(false);
        fTxtPeriodoRealizacaoFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        fTxtPeriodoRealizacaoFim.setToolTipText("Data do fim da realização da Exposição");

        fTxtPeriodoSubmissaoInicio.setEditable(false);
        fTxtPeriodoSubmissaoInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        fTxtPeriodoSubmissaoInicio.setToolTipText("Data do início da submissão da Exposição");

        fTxtPeriodoSubmissaoFim.setEditable(false);
        fTxtPeriodoSubmissaoFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        fTxtPeriodoSubmissaoFim.setToolTipText("Data do fim da submissão da Exposição");

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPeriodoRealizacao)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPeriodoRealizacaoInicio)
                            .addComponent(lblPeriodoRealizacaoFim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fTxtPeriodoRealizacaoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(fTxtPeriodoRealizacaoFim))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPeriodoSubmissao)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPeriodoSubmissaoInicio)
                            .addComponent(lblPeriodoSubmissaoFim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fTxtPeriodoSubmissaoFim, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(fTxtPeriodoSubmissaoInicio))))
                .addContainerGap())
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriodoRealizacao)
                    .addComponent(lblPeriodoSubmissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriodoRealizacaoInicio)
                    .addComponent(lblPeriodoSubmissaoInicio)
                    .addComponent(fTxtPeriodoRealizacaoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTxtPeriodoSubmissaoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriodoRealizacaoFim)
                    .addComponent(lblPeriodoSubmissaoFim)
                    .addComponent(fTxtPeriodoRealizacaoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTxtPeriodoSubmissaoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSouthLayout = new javax.swing.GroupLayout(jPanelSouth);
        jPanelSouth.setLayout(jPanelSouthLayout);
        jPanelSouthLayout.setHorizontalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSouthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
        );
        jPanelSouthLayout.setVerticalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSouthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jLstOrganizadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelSouth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelCenter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelNorth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelNorth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSouth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JFormattedTextField fTxtPeriodoRealizacaoFim;
    private javax.swing.JFormattedTextField fTxtPeriodoRealizacaoInicio;
    private javax.swing.JFormattedTextField fTxtPeriodoSubmissaoFim;
    private javax.swing.JFormattedTextField fTxtPeriodoSubmissaoInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Organizador> jLstOrganizadores;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtGestor;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblPeriodoRealizacao;
    private javax.swing.JLabel lblPeriodoRealizacaoFim;
    private javax.swing.JLabel lblPeriodoRealizacaoInicio;
    private javax.swing.JLabel lblPeriodoSubmissao;
    private javax.swing.JLabel lblPeriodoSubmissaoFim;
    private javax.swing.JLabel lblPeriodoSubmissaoInicio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
