/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui.organizador;

import java.awt.Component;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import lapr.project.controller.organizador.AtribuirCandidaturaController;
import lapr.project.model.submissions.Atribuicao;
import lapr.project.model.submissions.Candidatura;
import lapr.project.model.exhibitions.CentroExposicoes;
import lapr.project.model.exhibitions.Exposicao;
import lapr.project.model.mecanismos.MecanismoAtribuicao;
import lapr.project.model.users.FAE;

/**
 *
 * @author Sara Silva
 */
public class AtribuicaoTempListUI extends javax.swing.JFrame {

    private AtribuirCandidaturaController controller;
    private List<Atribuicao> atribuicaoList;

    /**
     * Creates new form AtribuirCandidaturaUI
     */
    public AtribuicaoTempListUI(AtribuirCandidaturaController atribuirCandidaturaController) {
        this.controller = atribuirCandidaturaController;
        this.atribuicaoList = controller.getListaAtribuicoes();
        
        super.setTitle("Lista Atribuicao");
        
        initComponents();
        inicializarLista();
        
        super.setLocationRelativeTo(null);
        super.setVisible(true);
    }
    
    private void inicializarLista(){
        for (Atribuicao atribuicao : atribuicaoList) {
            listAtribuicoes.add(atribuicao.getFae().getUtilizador().getUsername() 
                    + " - " + atribuicao.getCandidatura().getNomeEmpresa());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDecline = new javax.swing.JButton();
        jButtonAccept = new javax.swing.JButton();
        listAtribuicoes = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonDecline.setText("Cancelar");
        jButtonDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeclineActionPerformed(evt);
            }
        });

        jButtonAccept.setText("Aceitar");
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listAtribuicoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDecline, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jButtonAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listAtribuicoes, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDecline)
                    .addComponent(jButtonAccept))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptActionPerformed
        if (this.controller.registarAtribuicoes()) {
            JOptionPane.showMessageDialog(AtribuicaoTempListUI.this,
                    "Atribuicoes definidas com sucesso", "Lista Atribuicao", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(AtribuicaoTempListUI.this,
                    "Erro na definicao de Atribuicoes", "Lista Atribuicao", JOptionPane.ERROR_MESSAGE);
        }
        dispose();
    }//GEN-LAST:event_jButtonAcceptActionPerformed

    private void jButtonDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeclineActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonDeclineActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonDecline;
    private java.awt.List listAtribuicoes;
    // End of variables declaration//GEN-END:variables
}
